#!/bin/sh

# Set the script name and version
SCRIPT_NAME="nixpkg"
SCRIPT_VERSION="3.0"

# Define a function to call the Python script with sudo
sudo_call() {
  sudo python3 ~/scripts/python/main.py "$@"
}

# Define a function to call the Python script without sudo
nosudo_call() {
  python3 ~/scripts/python/main.py "$@"
}

# Main script logic
case $1 in
  # Actions that require sudo
  install|update|remove|restore|backup)
    sudo_call "$@"
    ;;
  # Actions that don't require sudo
  search|list|snapshot|add-category)
    nosudo_call "$@"
    ;;
  # Help option
  --help)
    nosudo_call --help
    ;;
  # Default case: show usage message
  *)
    echo "Usage: $SCRIPT_NAME <action> [<package/query>]"
    echo "Run '$SCRIPT_NAME --help' for more information."
    ;;
esac
