#!/bin/sh

# Set the script name and version
SCRIPT_NAME="nixpkg"
SCRIPT_VERSION="3.0"

# Set the script usage message
USAGE="Usage: $SCRIPT_NAME <action> [<package/query>]

Actions:
  install         Install packages
  remove          Remove packages
  search          Search packages
  list            List installed packages
  list-categories List categories
  update          Update NixOS
  snapshot        Create a snapshot
  restore         Restore from a snapshot
  add-category    Add a category

Options:
  --category      Specify a category for install/remove actions
  --help          Show this help message

Version: $SCRIPT_VERSION"

# Check if the user provided the --help option
if [ "$1" == "--help" ]; then
  echo "$USAGE"
  exit 0
fi

# Call the Python script with the provided arguments
sudo python3 python/main.py "$@"
